---
name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          sudo apt-get install portaudio19-dev python-pyaudio
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio
          # pip install custom_py_libs/PyAudio-0.2.11-cp39-cp39-win_amd64.whl
      - name: Test with pytest
        run: |
          pytest
